const constants = {
  ROLES: {
    ADMIN: "ADMIN",
    STAFF: "STAFF",
    CUSTOMER: "CUSTOMER",
  },

  ORDER_STATUS: {
    PENDING: "PENDING",
    PAID: "PAID",
    CANCELLED: "CANCELLED",
    REFUND_PENDING: "REFUND_PENDING",
    REFUNDED: "REFUNDED",
  },

  PRODUCT_TYPES: {
    MODEL: "MODEL",
    MATERIAL: "MATERIAL",
    TOOL: "TOOL",
  },

  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },

  HTTP_CODES: {
    // Success
    OK: 200,
    CREATED: 201,
    NOCONTENT: 204,

    // Client Error
    BAD_REQUESTED: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    CONFLICT: 409,
    UNPROCESSABLE_ENTITY: 422,
    TOO_MANY_REQUESTS: 429,

    // Server error
    INTERNAL_SERVER_ERROR: 500,
  },

  PRISMA_ERRORS: {
    VALUE_TOO_LONG: "P2000",
    RECORD_NOT_FOUND: "P2001",
    DUPLICATE: "P2002",
    FOREIGN_KEY: "P2003",
    CONSTRAINT_FAILED: "P2004",
    INVALID_VALUE_TYPE: "P2005",
    INVALID_VALUE: "P2006",
    VALIDATION_FAILED: "P2007",
    QUERY_PARSING_FAILED: "P2008",
    QUERY_VALIDATION_FAILED: "P2009",
    RAW_QUERY_FAILED: "P2010",
    NULL_CONSTRAINT: "P2011",
    MISSING_MAPPED_VALUE: "P2012",
    MISSING_REQUIRED_VALUE: "P2013",
    RELATION_VIOLATION: "P2014",
    RELATED_RECORD_NOT_FOUND: "P2015",
    INTERPRETATION_ERROR: "P2016",
    RECORDS_NOT_CONNECTED: "P2017",
    REQUIRED_CONN_NOT_FOUND: "P2018",
    INPUT_ERROR: "P2019",
    VALUE_OUT_OF_RANGE: "P2020",
    COMPILE_ERROR: "P2021",
    COLUMN_DOES_NOT_EXIST: "P2022",
    INCONSISTENT_COL_COUNT: "P2023",
    CONNECTION_TIMEOUT: "P2024",
    NOT_FOUND: "P2025",
    UNSUPPORTED_FEATURE: "P2026",
    MULTIPLE_RECORDS_FOUND: "P2027",
    API_ERROR: "P2028",
    TX_FAILED: "P2030",
  },
};

module.exports = constants;
